/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nachocano/gsuite-source/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDriveSources implements DriveSourceInterface
type FakeDriveSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var drivesourcesResource = schema.GroupVersionResource{Group: "sources.nachocano.org", Version: "v1alpha1", Resource: "drivesources"}

var drivesourcesKind = schema.GroupVersionKind{Group: "sources.nachocano.org", Version: "v1alpha1", Kind: "DriveSource"}

// Get takes name of the driveSource, and returns the corresponding driveSource object, and an error if there is any.
func (c *FakeDriveSources) Get(name string, options v1.GetOptions) (result *v1alpha1.DriveSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(drivesourcesResource, c.ns, name), &v1alpha1.DriveSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DriveSource), err
}

// List takes label and field selectors, and returns the list of DriveSources that match those selectors.
func (c *FakeDriveSources) List(opts v1.ListOptions) (result *v1alpha1.DriveSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(drivesourcesResource, drivesourcesKind, c.ns, opts), &v1alpha1.DriveSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DriveSourceList{ListMeta: obj.(*v1alpha1.DriveSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.DriveSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested driveSources.
func (c *FakeDriveSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(drivesourcesResource, c.ns, opts))

}

// Create takes the representation of a driveSource and creates it.  Returns the server's representation of the driveSource, and an error, if there is any.
func (c *FakeDriveSources) Create(driveSource *v1alpha1.DriveSource) (result *v1alpha1.DriveSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(drivesourcesResource, c.ns, driveSource), &v1alpha1.DriveSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DriveSource), err
}

// Update takes the representation of a driveSource and updates it. Returns the server's representation of the driveSource, and an error, if there is any.
func (c *FakeDriveSources) Update(driveSource *v1alpha1.DriveSource) (result *v1alpha1.DriveSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(drivesourcesResource, c.ns, driveSource), &v1alpha1.DriveSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DriveSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDriveSources) UpdateStatus(driveSource *v1alpha1.DriveSource) (*v1alpha1.DriveSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(drivesourcesResource, "status", c.ns, driveSource), &v1alpha1.DriveSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DriveSource), err
}

// Delete takes name of the driveSource and deletes it. Returns an error if one occurs.
func (c *FakeDriveSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(drivesourcesResource, c.ns, name), &v1alpha1.DriveSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDriveSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(drivesourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DriveSourceList{})
	return err
}

// Patch applies the patch and returns the patched driveSource.
func (c *FakeDriveSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DriveSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(drivesourcesResource, c.ns, name, data, subresources...), &v1alpha1.DriveSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DriveSource), err
}
