/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/nachocano/gsuite-source/pkg/apis/sources/v1alpha1"
	scheme "github.com/nachocano/gsuite-source/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CalendarSourcesGetter has a method to return a CalendarSourceInterface.
// A group's client should implement this interface.
type CalendarSourcesGetter interface {
	CalendarSources(namespace string) CalendarSourceInterface
}

// CalendarSourceInterface has methods to work with CalendarSource resources.
type CalendarSourceInterface interface {
	Create(*v1alpha1.CalendarSource) (*v1alpha1.CalendarSource, error)
	Update(*v1alpha1.CalendarSource) (*v1alpha1.CalendarSource, error)
	UpdateStatus(*v1alpha1.CalendarSource) (*v1alpha1.CalendarSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CalendarSource, error)
	List(opts v1.ListOptions) (*v1alpha1.CalendarSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CalendarSource, err error)
	CalendarSourceExpansion
}

// calendarSources implements CalendarSourceInterface
type calendarSources struct {
	client rest.Interface
	ns     string
}

// newCalendarSources returns a CalendarSources
func newCalendarSources(c *SourcesV1alpha1Client, namespace string) *calendarSources {
	return &calendarSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the calendarSource, and returns the corresponding calendarSource object, and an error if there is any.
func (c *calendarSources) Get(name string, options v1.GetOptions) (result *v1alpha1.CalendarSource, err error) {
	result = &v1alpha1.CalendarSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("calendarsources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CalendarSources that match those selectors.
func (c *calendarSources) List(opts v1.ListOptions) (result *v1alpha1.CalendarSourceList, err error) {
	result = &v1alpha1.CalendarSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("calendarsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested calendarSources.
func (c *calendarSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("calendarsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a calendarSource and creates it.  Returns the server's representation of the calendarSource, and an error, if there is any.
func (c *calendarSources) Create(calendarSource *v1alpha1.CalendarSource) (result *v1alpha1.CalendarSource, err error) {
	result = &v1alpha1.CalendarSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("calendarsources").
		Body(calendarSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a calendarSource and updates it. Returns the server's representation of the calendarSource, and an error, if there is any.
func (c *calendarSources) Update(calendarSource *v1alpha1.CalendarSource) (result *v1alpha1.CalendarSource, err error) {
	result = &v1alpha1.CalendarSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("calendarsources").
		Name(calendarSource.Name).
		Body(calendarSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *calendarSources) UpdateStatus(calendarSource *v1alpha1.CalendarSource) (result *v1alpha1.CalendarSource, err error) {
	result = &v1alpha1.CalendarSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("calendarsources").
		Name(calendarSource.Name).
		SubResource("status").
		Body(calendarSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the calendarSource and deletes it. Returns an error if one occurs.
func (c *calendarSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("calendarsources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *calendarSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("calendarsources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched calendarSource.
func (c *calendarSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CalendarSource, err error) {
	result = &v1alpha1.CalendarSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("calendarsources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
