/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/nachocano/gsuite-source/pkg/apis/sources/v1alpha1"
	scheme "github.com/nachocano/gsuite-source/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DriveSourcesGetter has a method to return a DriveSourceInterface.
// A group's client should implement this interface.
type DriveSourcesGetter interface {
	DriveSources(namespace string) DriveSourceInterface
}

// DriveSourceInterface has methods to work with DriveSource resources.
type DriveSourceInterface interface {
	Create(*v1alpha1.DriveSource) (*v1alpha1.DriveSource, error)
	Update(*v1alpha1.DriveSource) (*v1alpha1.DriveSource, error)
	UpdateStatus(*v1alpha1.DriveSource) (*v1alpha1.DriveSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DriveSource, error)
	List(opts v1.ListOptions) (*v1alpha1.DriveSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DriveSource, err error)
	DriveSourceExpansion
}

// driveSources implements DriveSourceInterface
type driveSources struct {
	client rest.Interface
	ns     string
}

// newDriveSources returns a DriveSources
func newDriveSources(c *SourcesV1alpha1Client, namespace string) *driveSources {
	return &driveSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the driveSource, and returns the corresponding driveSource object, and an error if there is any.
func (c *driveSources) Get(name string, options v1.GetOptions) (result *v1alpha1.DriveSource, err error) {
	result = &v1alpha1.DriveSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("drivesources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DriveSources that match those selectors.
func (c *driveSources) List(opts v1.ListOptions) (result *v1alpha1.DriveSourceList, err error) {
	result = &v1alpha1.DriveSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("drivesources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested driveSources.
func (c *driveSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("drivesources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a driveSource and creates it.  Returns the server's representation of the driveSource, and an error, if there is any.
func (c *driveSources) Create(driveSource *v1alpha1.DriveSource) (result *v1alpha1.DriveSource, err error) {
	result = &v1alpha1.DriveSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("drivesources").
		Body(driveSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a driveSource and updates it. Returns the server's representation of the driveSource, and an error, if there is any.
func (c *driveSources) Update(driveSource *v1alpha1.DriveSource) (result *v1alpha1.DriveSource, err error) {
	result = &v1alpha1.DriveSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("drivesources").
		Name(driveSource.Name).
		Body(driveSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *driveSources) UpdateStatus(driveSource *v1alpha1.DriveSource) (result *v1alpha1.DriveSource, err error) {
	result = &v1alpha1.DriveSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("drivesources").
		Name(driveSource.Name).
		SubResource("status").
		Body(driveSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the driveSource and deletes it. Returns an error if one occurs.
func (c *driveSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("drivesources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *driveSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("drivesources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched driveSource.
func (c *driveSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DriveSource, err error) {
	result = &v1alpha1.DriveSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("drivesources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
