/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/nachocano/gsuite-source/pkg/apis/sources/v1alpha1"
	scheme "github.com/nachocano/gsuite-source/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SheetsSourcesGetter has a method to return a SheetsSourceInterface.
// A group's client should implement this interface.
type SheetsSourcesGetter interface {
	SheetsSources(namespace string) SheetsSourceInterface
}

// SheetsSourceInterface has methods to work with SheetsSource resources.
type SheetsSourceInterface interface {
	Create(*v1alpha1.SheetsSource) (*v1alpha1.SheetsSource, error)
	Update(*v1alpha1.SheetsSource) (*v1alpha1.SheetsSource, error)
	UpdateStatus(*v1alpha1.SheetsSource) (*v1alpha1.SheetsSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SheetsSource, error)
	List(opts v1.ListOptions) (*v1alpha1.SheetsSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SheetsSource, err error)
	SheetsSourceExpansion
}

// sheetsSources implements SheetsSourceInterface
type sheetsSources struct {
	client rest.Interface
	ns     string
}

// newSheetsSources returns a SheetsSources
func newSheetsSources(c *SourcesV1alpha1Client, namespace string) *sheetsSources {
	return &sheetsSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sheetsSource, and returns the corresponding sheetsSource object, and an error if there is any.
func (c *sheetsSources) Get(name string, options v1.GetOptions) (result *v1alpha1.SheetsSource, err error) {
	result = &v1alpha1.SheetsSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sheetssources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SheetsSources that match those selectors.
func (c *sheetsSources) List(opts v1.ListOptions) (result *v1alpha1.SheetsSourceList, err error) {
	result = &v1alpha1.SheetsSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sheetssources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sheetsSources.
func (c *sheetsSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sheetssources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a sheetsSource and creates it.  Returns the server's representation of the sheetsSource, and an error, if there is any.
func (c *sheetsSources) Create(sheetsSource *v1alpha1.SheetsSource) (result *v1alpha1.SheetsSource, err error) {
	result = &v1alpha1.SheetsSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sheetssources").
		Body(sheetsSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sheetsSource and updates it. Returns the server's representation of the sheetsSource, and an error, if there is any.
func (c *sheetsSources) Update(sheetsSource *v1alpha1.SheetsSource) (result *v1alpha1.SheetsSource, err error) {
	result = &v1alpha1.SheetsSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sheetssources").
		Name(sheetsSource.Name).
		Body(sheetsSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sheetsSources) UpdateStatus(sheetsSource *v1alpha1.SheetsSource) (result *v1alpha1.SheetsSource, err error) {
	result = &v1alpha1.SheetsSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sheetssources").
		Name(sheetsSource.Name).
		SubResource("status").
		Body(sheetsSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the sheetsSource and deletes it. Returns an error if one occurs.
func (c *sheetsSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sheetssources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sheetsSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sheetssources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sheetsSource.
func (c *sheetsSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SheetsSource, err error) {
	result = &v1alpha1.SheetsSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sheetssources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
