# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: gsuite-controller-manager
  name: gsuite-controller-manager
  namespace: gsuite-sources
spec:
  selector:
    matchLabels:
      control-plane: gsuite-controller-manager
  serviceName: gsuite-controller-manager
  template:
    metadata:
      labels:
        control-plane: gsuite-controller-manager
    spec:
      containers:
        - image: github.com/nachocano/gsuite-source/cmd/manager
          name: manager
          env:
            # If this variable is set, then the authentication is done automatically by the client.
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: SHEETS_RA_IMAGE
              value: github.com/nachocano/gsuite-source/cmd/sheets_receive_adapter
            - name: CALENDAR_RA_IMAGE
              value: github.com/nachocano/gsuite-source/cmd/calendar_receive_adapter
          volumeMounts:
            - name: gcp-key
              mountPath: /var/secrets/google
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 20m
              memory: 20Mi
      volumes:
        - name: gcp-key
          secret:
            secretName: gsuite-source-key
      serviceAccount: gsuite-controller-manager
      terminationGracePeriodSeconds: 10
